### ISSUE TITLE
Замечания по Epic 0

### ISSUE THREAD

**Issue by vaszol** [vaszol/practicum-android-diploma#64]
По итогу ревью:

- [ ] .idea нужно добавить в gitignore, чтобы не пушить эти файлы
https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837141759
- [ ] вынести параметры как private const val
https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837143424
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837144092
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837144191
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837144775
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837145066
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837145753
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837145826
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837146100
- [ ] интерсептор к retrofit https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837147552
- [ ] https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837149009
- [ ] Serializable на data class https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837149611
- [ ] binding  https://github.com/vaszol/practicum-android-diploma/pull/45#discussion_r1837150184
